# Generated by Django 5.2.13 on 2026-05-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ID',
        ),
    ]
